---
format: html
---

*This document was originally developed as teaching material for UCSB's [Master of Environmental Data Science (MEDS)](https://bren.ucsb.edu/masters-programs/master-environmental-data-science/academics-meds) program.*

## {{< fa lightbulb title="Lightbulb">}} Some tips on navigating this document

If you've found your way here, welcome! Maybe you're excited to start on your website-building journey, or maybe you're just getting a feel for what Quarto is all about. Regardless, I hope you find these materials helpful. Some notes on what to expect:

This document is meant to introduce you to Quarto as a tool and framework for building websites, guide you through the process of creating your website (using either RStudio or a command line interface), and deploy it (for free) using GitHub Pages. The content covered here is only an introduction to the wonderful suite of tooling that Quarto provides! I encourage you to also explore [Posit](https://posit.co/)'s incredible [Quarto documentation](https://quarto.org/), as well as the seemingly endless list of awesome resources created by other Quarto users. Feel free to check out my follow-up workshop materials, [Customizing Quarto Websites using Sass & CSS](https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide) and [Adding a blog to your existing Quarto website](https://samanthacsik.github.io/talks_workshops/2022-10-24-quarto-blogs/).

You'll encounter some callout boxes throughout these materials, which are meant to provide additional tips, considerations, contexts:

::: {.callout-note collapse=true}
## Note (collapsed by default to minimize scrolling; click to expand)
This is a **note**, often providing additional context, clarification, resources, etc.
:::

::: {.callout-tip}
This is a **tip**, with suggested workflows, organizational tips, additional tools, etc.
:::

::: {.callout-important}
This is **important text** -- be sure to read these carefully as to not miss any important steps!
:::
