---
format: html
---

## {{< fa seedling title="Sprouted seedling" >}} Create the scaffolding for your website {#create-website-scaffolding}

::: callout-important
## Before getting started...

To follow along, you'll need:

-   [R](https://cloud.r-project.org/){target="_blank"} & [RStudio](https://posit.co/download/rstudio-desktop/#download){target="_blank"} installed 
-   [Quarto](https://quarto.org/docs/get-started/){target="_blank"} installed -- **Quarto is now included with RStudio v2022.07.1+ i.e. no need for a separate download / install if you have the latest version of RStudio**
-   [Git](https://git-scm.com/){target="_blank"} installed / configured
-   A [GitHub](https://github.com/){target="_blank"} account & a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#about-personal-access-tokens){target="_blank"} (PAT) set

Please refer to the [MEDS Installation Guide](https://ucsb-meds.github.io/MEDS-installation-guide/){target="_blank"} for detailed setup instructions (follow steps 1-7).
:::

This document reviews three ways to get started with using Quarto to build your website.

(1) `r fontawesome::fa("r-project", fill = "#5A5A5A", a11y = "sem")` Using the RStudio IDE
(2) `r fontawesome::fa("terminal", fill = "#5A5A5A", a11y = "sem")` Through the command line  
(3) `r fontawesome::fa("plus", fill = "#5A5A5A", a11y = "sem")` Using the Positron IDE

The order of operations is slightly different depending on which approach you decide to take, but the concepts remain the same.