---
format: 
  html:
    theme: meds-website-styles.scss
    mainfont: Nunito
    toc: true
    toc-location: left
    toc-depth: 2
    smooth-scroll: true
---

## {{< fa forward title="Fast forward symbol" >}} Looking forward {#looking-forward}

You should now have a basic version of your website up and running 🎉 During Fall quarter, we'll learn how to:

a\. [customize the appearance of our site using Sass & CSS](https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide)

b\. [add a blog and blog posts to our websites](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/) 

c\. continue developing your online "brand"

In the meantime, explore some [current student & alumni websites](https://ucsb-meds.github.io/student_websites.html) (**Note:** MEDS class of 2022 used the [`{distill}`](https://rstudio.github.io/distill/website.html) package to build their websites) for inspiration, or dig into the [Quarto Website documentation](https://quarto.org/docs/websites/) if you're hoping to get started now on further customization.

## {{< fa star title="Star" >}} Additional resources to get you stoked about Quarto {#resources}

<!-- -   We don't talk about Quarto, by Alison Hill \| [`r fontawesome::fa("blog", fill = "#5A5A5A", a11y = "sem")` blog post](https://www.apreshill.com/blog/2022-04-we-dont-talk-about-quarto/) -->

-  Awesome Quarto (GitHub repository of curated Quarto resources), by Mickaël Canouil | [{{< fa brands github title="GitHub Octocat" >}} GitHub repo](https://github.com/mcanouil/awesome-quarto)

-   Reproducible Authoring with Quarto, by Mine Çetinkaya-Rundel \| [{{< fa desktop title="Desktop computer" >}}  slides](https://mine-cetinkaya-rundel.github.io/2022-repro-toronto/#/title-slide) \| [{{< fa video title="video camera" >}} recording](https://www.youtube.com/watch?v=6p4vOKS6Xls)

-   Hello Quarto! A Chat with NASA Openscapes, Co-Hosted with R-Ladies Santa Barbara \| [{{< fa blog title="Blog symbol" >}} blog post](https://www.openscapes.org/blog/2022/06/22/hello-quarto/) \| [{{< fa video title="video camera" >}} recording](https://www.youtube.com/watch?v=azVAl343CIU)

-   rstudio::conf 2022 keynote, Hello Quarto, by Julie Lowndes and Mine Çetinkaya-Rundel \| [{{< fa video title="video camera" >}} recording](https://www.rstudio.com/conference/2022/keynotes/collaborate-with-quarto/)
