---
format: 
  html:
    theme: meds-website-styles.scss
    mainfont: Nunito
    toc: true
    toc-location: left
    toc-depth: 2
    smooth-scroll: true
---

<!-- ::: {.callout-note collapse=true} -->
## {{< fa pause title="pause" >}} What if I want to create a Quarto website inside an *existing* GitHub repository?

The above instructions follow the **"create local website project (and initialize as a git repo) *first* > create upstream remote repo (on GitHub) *second*"** workflow. However, if you already have a remote GitHub repository that you want to use for your website, clone the GitHub repo, then run the following command in the command line:

```{bash filename="Command line / Terminal"}
#| eval: false
quarto create-project --type website
```

This adds the the default files (`_quarto.yml`, `.gitignore`, `index.qmd`, `about.qmd`, `styles.css`) for getting started on your website.

You may also use this approach if you already have an existing local directory of documents or project that you'd like to use as the directory for your website. First, navigate to that directory / open that project, then run the above command in the command line. 
<!-- ::: -->
